Fix YOLO.generate does not work for tiny yolo
When tried to create a tiny Yolo:
yolo_model = YOLO(model_path=log_dir + 'trained_weights_final.h5', classes_path=classes_path)
Error: "You are trying to load a weight file containing 24 layers into a model with 147 layers"
Try section attempted to  create a regular Yolo and load a tiny weight file, crashed without triggering the exception block where the tiny model will be loaded.

Changed to use explicit if else.